### PR TITLE
Check if inputs have changed. Fixes #1.

### LINKED ISSUE #1: Only publish if registry is updated
Although this registry does change pretty frequently, there are two-week spans when there is no change.

Suggestion: 
- Read the value of the 'Last-Modified' header from the build.js command line, if it is provided (package script reads this from a file)
- Put this value in an 'If-Modified-Since' header in the fetch.
- If fetch returns 304, stop processing the update (e.g. return a non-zero error code which should cause the workflow to stop)
- Write the Last-Modified header to stderr (package script saves this to a file with a )
- If there are no changes to the processed file, stop processing.  This could happen due to something changing in the registry that you don't care about, like an author's email address.
- Only if there is a substantive change, continue on to publishing the package.
- Your current reporting of retries would need to be removed or modified, or the build.js script could become node-specific and write files directly.

I would be happy to send a PR.

### LINKED ISSUE #2: Examples to new import attribute syntax
See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import/with).

The examples should probably use the current import syntax, not the one that was scrapped.  For example:

```js
import mediaTypes from 'iana-media-type' with { type: 'json' };
console.log({ mediaTypes, length: mediaTypes.length });
```

This still doesn't work in Firefox, unfortunately, but hopefully that gets fixed in a reasonable timeframe.  see [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1736059).

### PR DESCRIPTION
**Pull request by hildjj**
- Tweaked README.md language about JSON file in
the notes at the end.
- Tweaked index.js output so that prettier should
not need to modify it.

Depends on PR #3.

### CODE REVIEW

**Comment by AsherJingkongChen** [comment]
Hi, I am not sure why this is not a commit in #3. It duplicates #3 at some parts. May you close #3?

**Comment by AsherJingkongChen** [comment]
Sorry, I also need time to investigate it, especially how it differs from the original version.

**Comment by hildjj** [comment]
This builds on the changes in #3.  Happy to close that in favor of this instead of splitting it up.

**Comment by AsherJingkongChen** [comment]
Is there any case that we need `index.js` meanwhile `index.json` exists? Oh wait it preserves backward compatibility and adds caching tags.

File: build.js [hunk 1]
```diff
@@ -1,16 +1,39 @@
...
       'https://www.iana.org/assignments/media-types/media-types.xml',
-      {
-        redirect: 'follow',
-      },
+      init,
     );
     const { ok, status, statusText } = response;
+    if (status === 304) {
+      console.error(statusText);
+      process.exit(2);
```
Comment (AsherJingkongChen) [inline build.js]: Nice early exiting.

File: build.js [hunk 2]
```diff
@@ -40,8 +63,34 @@
...
+
+    // Make output match what prettier expects
+    output = output.replaceAll('"', "'");
+    output = output.replace("'\n\]", "',\n]");
+    fs.writeFileSync(
+      'index.js',
+      `\
+// @generated by build.js
+export const updated = new Date('${new Date().toISOString()}');
+export const lastModified = '${response.headers.get('last-modified')}';
```
Comment (AsherJingkongChen) [inline build.js]: Not safe, should escape `'`

File: build.js [hunk 3]
```diff
@@ -40,8 +63,34 @@
...
+    if (hex === previous?.hash) {
+      // There was a change to authors, etc. that we don't care about.
+      console.error('Inconsequential change to inputs');
+      process.exit(3);
+    }
+    fs.writeFileSync('index.json', output + '\n');
+
+    // Make output match what prettier expects
+    output = output.replaceAll('"', "'");
+    output = output.replace("'\n\]", "',\n]");
```
Comment (AsherJingkongChen) [inline build.js]: It just works.

File: build.js [hunk 4]
```diff
@@ -40,8 +63,34 @@
...
-    const output = mediaTypes;
-    console.log(JSON.stringify(output, undefined, 2));
+    let output = JSON.stringify(mediaTypes, undefined, 2);
+    const hash = createHash('sha256');
+    hash.update(output);
+    hash.update('\n');
+    const hex = hash.digest('hex');
+
+    if (hex === previous?.hash) {
+      // There was a change to authors, etc. that we don't care about.
```
Comment (AsherJingkongChen) [inline build.js]: Wait, is author information contained in `output`?

**Comment by AsherJingkongChen** [comment]
Hi, I have done reviewing the codes, but there are some comments that requires your thoughts.

File: build.js (hunk 4 above)
Comment (AsherJingkongChen) [reply build.js]: Wait, I understand it now. The snippet only executes if we successfully fetched the XML.

Comment (hildjj) [reply build.js]: Author information is in the input XML file.  Once the XML is processed, you would get the same exact list of mediatypes as the previous run, even though fetch returned 304.

File: build.js (hunk 3 above)
Comment (hildjj) [reply build.js]: Would you prefer to let prettier do this?  I can remove these lines.

Comment (AsherJingkongChen) [reply build.js]: Since the code snippet should have a meaningful change for `index.json`, prettier can happily format the files.

**Comment by AsherJingkongChen** [comment]
@hildjj Hi, your changes look great! I just made a few minor tweaks to ensure everything is LGTM—hope you don’t mind.

File: build.js [hunk 5]
```diff
@@ -22,20 +21,17 @@ try {
     };
     if (previous?.lastModified) {
       init.headers = new Headers({
-        'if-modified-since': previous.lastModified,
+        'if-modified-since': previous?.lastModified,
```
Comment (hildjj) [inline build.js]: No need for `?` here since we just checked it in the if statement.

File: build.js [hunk 6]
```diff
@@ -22,20 +21,17 @@ try {
...
     );
     const { ok, status, statusText } = response;
-    if (status === 304) {
-      console.error(statusText);
-      process.exit(2);
-    }
-    if (!ok) {
-      throw new Error(`HTTP ${status} ${statusText}`);
+    const statusTextPretty = `HTTP ${status} ${statusText}`;
+    if (!ok || status === 304) {
```
Comment (hildjj) [inline build.js]: This is incorrect in my opinion.  With this approach, you will retry 5 times with a 304 response.  Note that ok=false with a 304.

File: build.js [hunk 7]
```diff
@@ -63,37 +59,32 @@ try {
...
-    if (hex === previous?.hash) {
-      // There was a change to authors, etc. that we don't care about.
-      console.error('Inconsequential change to inputs');
-      process.exit(3);
+    const index = JSON.stringify(mediaTypes, null, 2) + '\n';
+    const hash = createHash('sha256').update(index).digest('hex');
+    const lastModified = response.headers.get('last-modified') || null;
+    const updated = new Date().toUTCString();
+    if (hash === previous?.hash) {
+      throw new Error('No relevant changes detected.');
```
Comment (hildjj) [inline build.js]: Same issue with the 304.  This will cause unnecessary retries.

**Review by hildjj — COMMENTED** [review]
The change to exceptions from process.exit has caused a few issues, I think.

File: build.js (hunk 5 above)
Comment (AsherJingkongChen) [reply build.js]: Right.

File: build.js (hunk 6 above)
Comment (AsherJingkongChen) [reply build.js]: Right.

File: build.js (hunk 7 above)
Comment (AsherJingkongChen) [reply build.js]: Yes.

**Comment by AsherJingkongChen** [comment]
> The change to exceptions from process.exit has caused a few issues, I think.

@hildjj Now the program early exits at the first try (if HTTP 304 and no relevant changes).

File: build.js [hunk 8]
```diff
@@ -21,17 +21,16 @@ try {
     };
     if (previous?.lastModified) {
       init.headers = new Headers({
-        'if-modified-since': previous?.lastModified,
+        'if-modified-since': previous.lastModified.toUTCString(),
```
Comment (hildjj) [inline build.js]: It's safer to use the EXACT string returned from the server, since doing date parsing and toJSON is quite likely to introduce changes.

Comment (hildjj) [reply build.js]: That would mean storing the date in index.js as a string, NOT as a date, as in my original.

**Review by hildjj — COMMENTED** [review]
Suggest storing last-modified as a string.

File: build.js (hunk 8 above)
Comment (AsherJingkongChen) [reply build.js]: yes

**Comment by hildjj** [comment]
LGTM.  Thanks!
